# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Título do album')),
                ('slug', models.SlugField(editable=False)),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição do album')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Album',
                'ordering': ['name'],
                'verbose_name_plural': 'Albuns',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('legend', models.TextField(blank=True, null=True, verbose_name='Legenda')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('image', models.ImageField(upload_to='fotos/%Y/%m')),
                ('photographer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Fotografo')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.Album', verbose_name='Album')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Foto',
                'ordering': ['title'],
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
